---
application:
  name: "peripheral-vision-training-v1"
  project: "peripheral-vision-training-V1"
  organization: "QoveryCommunity"
routers:
- name: "main-peripheral-vision-training-v1"
  routes:
  - application_name: "peripheral-vision-training-v1"
    paths:
    - "/*"
